replicaCount: 2

securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  capabilities:
    drop:
    - ALL
  privileged: false
  readOnlyRootFilesystem: true
  runAsGroup: 1001
  runAsUser: 1001

ui:
  color: "###ZARF_VAR_PODINFO_UI_COLOR###"
  message: "Hello There!"