# This is a basic workflow to help you get started with Actions

name: mage-ci

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
             export GOBIN=$(pwd)/.bin/go
             export PATH=$PATH:$GOBIN
             mkdir -p $(pwd)/.bin/go
             go install github.com/magefile/mage@latest
             mage -version
             
      - name: Install Zarf
        uses: defenseunicorns/setup-zarf@main
        with:
          # renovate: datasource=github-tags depName=defenseunicorns/zarf versioning=semver
          version: v0.29.2
      - name: Run mage zarf version
        run: | 
              export GOPATH=$(pwd)/.bin/go
              export PATH=$PATH:$GOPATH
              export MAGEFILE_VERBOSE=1
              mage -v build:zarfVersion
              
      - name: Run mage zarf build
        run: | 
              export GOPATH=$(pwd)/.bin/go
              export PATH=$PATH:$GOPATH
              export MAGEFILE_VERBOSE=1
              mage -v build:zarfBuild

